server:
  port: 80
logging:
  config: classpath:log4j2.xml
mybatis:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  type-aliases-package: com.baozi.entity
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://123.56.219.123:3306/test?characterEncoding=UTF-8
    username: root
    password: Zz971886506
    hikari:
      pool-name: HikariPool
      minimum-idle: 5
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  aop:
    proxy-target-class: true
  redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password:
      jedis:
        pool:
          #最大连接数
          max-active: 8
          #最大阻塞等待时间(负数表示没限制)
          max-wait: -1
          #最大空闲
          max-idle: 8
          #最小空闲
          min-idle: 0
      #连接超时时间
      timeout: 10000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          max-wait: -1ms
          min-idle: 0
      shutdown-timeout: 100ms
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 123.56.219.123:9200
      repositories:
        enabled: true
  elasticsearch:
      rest:
        uris: 123.56.219.123:9200
  resources:
    static-locations: classpath:/static/,classpath:/templates/
  thymeleaf:
    cache: false
  mvc:
    favicon:
      enabled: true