# 开启AOP代理
spring.aop.proxy-target-class: true
# DruidDataSource数据源配置
spring.datasource.type: com.alibaba.druid.pool.DruidDataSource
spring.datasource.driver-class-name: com.mysql.jdbc.Driver
spring.datasource.url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=UTF-8
spring.datasource.username: root
spring.datasource.password: root
spring.datasource.initialSize: 5
spring.datasource.minIdle: 5
spring.datasource.maxWait: 60000
spring.datasource.maxActive: 20
spring.datasource.timeBetweenEvictionRunsMillis: 60000
spring.datasource.minEvictableIdleTimeMillis: 300000
spring.datasource.validationQuery: SELECT 1 FROM DUAL
spring.datasource.testWhileIdle: true
spring.datasource.testOnBorrow: false
spring.datasource.testOnReturn: false
spring.datasource.poolPreparedStatements: true
spring.datasource.maxPoolPreparedStatementPerConnectionSize: 20
spring.datasource.filters: stat,wall,log4j
spring.datasource.connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

# redis缓存配置
# Redis数据库索引（默认为0）
spring.redis.database: 0
# Redis服务器地址
spring.redis.host: 127.0.0.1
# Redis服务器连接端口
spring.redis.port: 6379
# Redis服务器连接密码（默认为空）
spring.redis.password: Credit2016Admin
# 连接池最大连接数（使用负值表示没有限制）
spring.redis.pool.max-active: 10
# 连接池最大阻塞等待时间（使用负值表示没有限制）
spring.redis.pool.max-wait: 60
# 连接池中的最大空闲连接
spring.redis.pool.max-idle: 5
# 连接池中的最小空闲连接
spring.redis.pool.min-idle: 2
# 连接超时时间（毫秒）
spring.redis.timeout: 60

# 服务端口配置  上下文配置
server.port: 8080
#server.context-path: /becatBoot

# log4j2配置打印日志log
logging.config: classpath:log4j2.xml

# mybatis配置
mybatis.mapper-locations: classpath:/mapper/**/*Mapper.xml
mybatis.type-aliases-package: com.baozi.entity

# thymeleaf模板配置
spring.thymeleaf.cache: false
spring.thymeleaf.check-template: false

# 静态资源映射
resources.static-locations: classpath:/static/,classpath:/templates/

# 开启favicon配置 显示favicon图标
mvc.favicon.enabled: true